- name: ensure dir for redis
  file:
    path: "{{ data_dir }}/redis/"
    state: directory
    mode: "0755" 

- name: template file
  template:
    src: "{{ item }}"
    dest: "{{ data_dir }}/redis/{{ item | splitext | first }}"
    mode: "0755"
  with_items:
    - docker-compose.yml.j2
    - redis.conf.j2
    - sentinel-1.conf.j2

- name: install redisr master 
  shell: "docker-compose -f docker-compose.yml up -d"
  args:
    chdir: "{{ data_dir }}/redis" 
